services:

  product_db:
    image: cockroachdb/cockroach:v23.1.11
    hostname: cockroachdb
    command: start-single-node --insecure
    ports:
      - 26001:26257
  
  product_db_init:
    image: cockroachdb/cockroach:v23.1.11
    volumes:
      - ./init_product.sh:/init_product.sh
    entrypoint: "/bin/bash"
    command: /init_product.sh
    depends_on:
      - product_db

  stock_db:
    image: cockroachdb/cockroach:v23.1.11
    hostname: cockroachdb
    command: start-single-node --insecure
    ports:
      - 26002:26257
  
  stock_db_init:
    image: cockroachdb/cockroach:v23.1.11
    volumes:
      - ./init_stock.sh:/init_stock.sh
    entrypoint: "/bin/bash"
    command: /init_stock.sh
    depends_on:
      - stock_db
  
  products_svc:
    image: products_svc
    hostname: products
    build:
      context: services/product
    ports:
      - 3001:3000
    depends_on:
      - product_db
      - product_db_init
  
  stock_svc:
    image: stock_svc
    hostname: stock
    build:
      context: services/stock
    ports:
      - 3002:3000
    depends_on:
      - stock_db
      - stock_db_init
