services:

  scylla:
    image: scylladb/scylla:5.4
    hostname: scylla
    container_name: scylla
    ports:
      - 9042:9042
    networks:
      - app-network

  indexer:
    image: indexer
    hostname: indexer
    container_name: indexer
    build:
      context: services/indexer
    environment:
      SCYLLA_URL: scylla:9042
      INDEX_URL: postgres://postgres:password@index:5432/postgres?sslmode=disable
    depends_on:
      - index
    networks:
      - app-network
  
  index:
    image: postgres:15.2-alpine
    hostname: index
    container_name: index
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge