services:

  redis:
    image: redis:7.2.3-alpine3.18
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    restart: always
    command: redis-server
    networks:
      - app-network
  
  index:
    image: cockroachdb/cockroach:v23.1.11
    hostname: index
    container_name: index
    command: start-single-node --insecure
    ports:
      - 26257:26257
    networks:
      - app-network

  indexer:
    image: indexer
    hostname: indexer
    build:
      context: services/indexer
    ports:
      - 3001:3000
    environment:
      REDIS_URL: redis:6379
      INDEX_URL: postgres://root@index:26257/defaultdb?sslmode=disable
    depends_on:
      - index
    networks:
      - app-network

networks:
  app-network:
    driver: bridge