services:

  localstack: 
    image: localstack/localstack:latest
    environment: 
      - DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=s3,lambda,logs,iam
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - '4566-4583:4566-4583'
    privileged: true