services:

  node1:
    image: cockroachdb/cockroach:v23.1.11
    hostname: node1
    container_name: node1
    command: start --insecure --join=node1,node2,node3 --locality=region=us-east-1,zone=us-east-1a
    ports:
      - 26001:26257
      - 8001:8080
    networks:
      - app-network

  node2:
    image: cockroachdb/cockroach:v23.1.11
    hostname: node2
    container_name: node2
    command: start --insecure --join=node1,node2,node3 --locality=region=eu-central-1,zone=eu-central-1a
    ports:
      - 26002:26257
      - 8002:8080
    networks:
      - app-network

  node3:
    image: cockroachdb/cockroach:v23.1.11
    hostname: node3
    container_name: tertiary
    command: start --insecure --join=node1,node2,node3 --locality=region=us-west-2,zone=us-west-2a
    ports:
      - 26003:26257
      - 8003:8080
    networks:
      - app-network

  haproxy:
    hostname: haproxy
    image: timveil/dynamic-haproxy:latest
    ports:
      - 26257:26257
      - 8080:8080
      - 8081:8081
    environment:
      - NODES=node1 node2 node3
    links:
      - node1
      - node2
      - node3
    networks:
    - app-network

networks:
  app-network:
    driver: bridge
